library(data.table)
library(reshape)
library(dplyr)

setwd("/Users/meghanjordan/data/SET1")

########################################
# Tivaouane Magal:                     #
# SET1S months 1 and 2 and site id:    #
# Load, Clean, Merge Set 1 sms files   #
# Load, Clean, Merge siteID and latLon #
########################################

#First twelve loading of multiple files from SET1 SMS data 
first_set <-read.csv(file="2013_01_08_00.csv")
second_set <- read.csv(file="ay-SET1S_01.csv")
third_set <- read.csv(file="az-SET1S_01.csv")
fourth_set <- read.csv(file="ba-SET1S_01.csv")
fifth_set <- read.csv(file="bb-SET1S_01.csv")
sixth_set <- read.csv(file="bc-SET1S_01.csv")
seven_set <- read.csv(file="bd-SET1S_01.csv")
eight_set <- read.csv(file="be-SET1S_01.csv")
ninth_set <- read.csv(file="bf-SET1S_01.csv")
tenth_set <- read.csv(file="bg-SET1S_01.csv")
eleventh_set <- read.csv(file="bh-SET1S_01.csv")
twelveth_set <- read.csv(file="bi-SET1S_01.csv")

names(first_set) <- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(second_set) <- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(third_set) <- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(fourth_set) <- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(fifth_set) <- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(sixth_set) <- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(seven_set) <- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(eight_set) <- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(ninth_set) <- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(tenth_set) <- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(eleventh_set) <- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(twelveth_set)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")

#first merge
first_twelve_files <- rbind(first_set, second_set, third_set, fourth_set, fifth_set, sixth_set, seven_set, eight_set, ninth_set, tenth_set, eleventh_set, twelveth_set)
names(first_twelve_files) <- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")

rm(first_set, second_set, third_set, fourth_set,fifth_set, sixth_set, seven_set, eight_set, ninth_set, tenth_set, eleventh_set, twelveth_set)

#Second loading, file names changed to alpha for brevity
a <- read.csv(file="bj-SET1S_01.csv")
b <-read.csv(file="bk-SET1S_01.csv")
c <-read.csv(file="bl-SET1S_01.csv")
d<-read.csv(file="bm-SET1S_01.csv")
e <-read.csv(file="bn-SET1S_01.csv")
f <- read.csv(file="bo-SET1S_01.csv")
g <- read.csv(file = "bp-SET1S_01.csv")
h <- read.csv(file ="bq-SET1S_01.csv")
i <- read.csv(file="br-SET1S_01.csv")
j <-read.csv(file="bs-SET1S_01.csv")
k <- read.csv(file="bt-SET1S_01.csv")
l <- read.csv(file="bu-SET1S_01.csv")

names(a) <- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(b) <- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms"))
names(c) <- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(d) <- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(e)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(f)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(g)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(h)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(i)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(j)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(k)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(l)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")

second_twelve_files <-rbind(a, b, c, d, e, f, g, h, i, j, k, l)
rm(a, b, c, d, e, f, g, h, i, j, k, l)

#third loading 
bv <- read.csv(file="bv-SET1S_01.csv")
bw <- read.csv(file ="bw-SET1S_01.csv")
bx <- read.csv(file="bx-SET1S_01.csv")
by <- read.csv(file="by-SET1S_01.csv")
bz <- read.csv(file="bz-SET1S_01.csv")
ca <- read.csv(file="ca-SET1S_01.csv")
cb <- read.csv(file="cb-SET1S_01.csv")
cc <- read.csv(file="cc-SET1S_01.csv")
cd <- read.csv(file="cd-SET1S_01.csv")
ce <- read.csv(file ="ce-SET1S_01.csv")
cf <-read.csv(file="cf-SET1S_01.csv")
cg <- read.csv(file="cg-SET1S_01.csv")

names(bv) <- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(bw)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(bx)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(by)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(bz)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(ca)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(cb)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(cc)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(cd)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")         
names(ce)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(cf)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(cg)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")

third_twelve_files <- rbind(bv, bw, bx, by, bz, ca, cb, cc, cd, ce, cf, cg)
rm(bv, bw, bx, by, bz, ca, cb, cc, cd, ce, cf, cg)

#fourth loading 
ch <- read.csv(file="ch-SET1S_01.csv")
ci <- read.csv(file="ci-SET1S_01.csv")
cj <- read.csv(file="cj-SET1S_01.csv")
ck <- read.csv(file="ck-SET1S_01.csv")
cl <- read.csv(file="cl-SET1S_01.csv")
cm <- read.csv(file="cm-SET1S_01.csv")
cn <- read.csv(file="cn-SET1S_01.csv")
co <- read.csv(file="co-SET1S_01.csv")
cp <- read.csv(file="cp-SET1S_01.csv")
cq <- read.csv(file="cq-SET1S_01.csv")
cr <- read.csv(file="cr-SET1S_01.csv")
cs <- read.csv(file="cs-SET1S_01.csv")
names(ch) <- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(ci)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(cj)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(ck)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(cl)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(cm)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(cn)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(co)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(cp)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(cq)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(cr)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(cs)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
forth_twelve_files <- rbind(ch, ci, cj, ck, cl, cm, cn, co, cp, cq, cr, cs)
rm(ch, ci, cj, ck, cl, cm, cn, co, cp, cq, cr, cs)

#final ten files
ct <- read.csv(file="ct-SET1S_01.csv")
cu <- read.csv(file="cu-SET1S_01.csv")
cv <- read.csv(file="cv-SET1S_01.csv")
cw <- read.csv(file="cw-SET1S_01.csv")
cx <- read.csv(file="cx-SET1S_01.csv")
cy <- read.csv(file="cy-SET1S_01.csv")
cz <- read.csv(file="cz-SET1S_01.csv")
da <- read.csv(file="ca-SET1S_01.csv")
db <- read.csv(file="db-SET1S_01.csv")
dc <- read.csv(file="dc-SET1S_01.csv")
names(ct) <- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(cu)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(cv)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(cw)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(cx)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(cy)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(cz)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(da)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(db)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(dc)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
final_ten <- rbind(ct,cu, cv, cw, cx, cy, cz, da, db, dc)
rm(ct,cu, cv, cw, cx, cy, cz, da, db, dc)

#final merge of the set1s for month 1
set1s_m1 <- rbind(first_twelve_files, second_twelve_files, third_twelve_files, forth_twelve_files, final_ten)
rm(first_twelve_files, second_twelve_files, third_twelve_files, forth_twelve_files, final_ten)

#Loading and merge of set1s for month 2
aa <- read.csv(file="aa-SET1S_02.csv")
ab <- read.csv(file="ab-SET1S_02.csv")
ac <- read.csv(file="ac-SET1S_02.csv")
ad <- read.csv(file="ad-SET1S_02.csv")
ae <- read.csv(file="ae-SET1S_02.csv")
af <- read.csv(file="af-SET1S_02.csv")
ag <- read.csv(file="ag-SET1S_02.csv")
ah <- read.csv(file="ah-SET1S_02.csv")
ai <- read.csv(file="ai-SET1S_02.csv")
aj <- read.csv(file="aj-SET1S_02.csv")
ak <- read.csv(file="ak-SET1S_02.csv")
al <- read.csv(file="al-SET1S_02.csv")
am <- read.csv(file="am-SET1S_02.csv")
an <- read.csv(file="an-SET1S_02.csv")
ao <- read.csv(file="ao-SET1S_02.csv")
ap <- read.csv(file="ap-SET1S_02.csv")
aq <- read.csv(file="aq-SET1S_02.csv")
ar <- read.csv(file="ar-SET1S_02.csv")
as <- read.csv(file="as-SET1S_02.csv")
names(aa)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(ab)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(ac)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(ad)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(ae)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(af)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(ag)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(ah)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(ai)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(aj)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(ak)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(al)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(am)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(an)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(ao)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(ap)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(aq)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(ar)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
names(as)<- c("timestamp", "outgoing_siteid", "incoming_siteid", "number_of_sms")
set1s_m2 <- rbind(aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as)
rm(aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as)


#Load siteID and ARRID
ARR_ID <- read.csv(file="SENEGAL_ARR.csv")
SITE_ID <-read.csv(file="SITE_ARR_LONLAT.csv")

#merge SITE_ID and ARR_ID
names(ARR_ID) <- c("arr_id", "region", "dept", "district")

arr_id_list <- merge(ARR_ID, SITE_ID, by="arr_id")


#merge set1s_m1 and set1s_m2
sms_m1_m2 <- rbind(set1s_m1, set1s_m2)

#save
saveRDS(sms_m1_m2, "sms_m1_m2.rds")
saveRDS(arr_id_list, "arr_id_list.rds")

